### ISSUE TITLE
bug: Dep injection error when using bound method for parsing

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#176]
```python
# repro.py
import sys
import cappa
from dataclasses import dataclass
from typing import Annotated
from pathlib import Path


class Config:
    @classmethod
    def from_file(cls, path: str | Path):
        return cls()


@cappa.command(name="command")
@dataclass(kw_only=True)
class Command:
    config: Annotated[
        Config | None,
        cappa.Arg(
            short="-c",
            long=True,
            parse=Config.from_file,
            help="Path to the configuration file.",
        ),
    ] = None



def main(args: list[str] | None = None) -> int:
    return cappa.invoke(Command, argv=args)


if __name__ == "__main__":
    sys.exit(main())
```

```bash
python repro.py
```

```pytb
Traceback (most recent call last):
  File "/media/data/dev/insiders-project/repro.py", line 35, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/data/dev/insiders-project/repro.py", line 31, in main
    return cappa.invoke(Command, argv=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/base.py", line 131, in invoke
    command, parsed_command, instance, concrete_output = parse_command(
                                                         ^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/base.py", line 239, in parse_command
    command: Command = collect(
                       ^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/base.py", line 357, in collect
    command = Command.collect(command)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/command.py", line 179, in collect
    arg_defs: list[Arg] = Arg.collect(
                          ^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/arg.py", line 228, in collect
    normalized_arg = arg.normalize(
                     ^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/arg.py", line 269, in normalize
    parse = infer_parse(self, type_view)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/arg.py", line 582, in infer_parse
    return evaluate_parse(parse, type_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/parse.py", line 261, in evaluate_parse
    **fulfill_deps(
      ^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/invoke.py", line 307, in fulfill_deps
    value = fulfilled_deps[cls]
            ~~~~~~~~~~~~~~^^^^^
KeyError: <class '__main__.Config'>
```

It looks like the dependency injection system kicks in because it thinks that `Config.from_file` accepts more than one argument (by looking at the real signature, not taking into account it's a bound method)? Not sure, as the docs mention one can use `parse=json.loads`, which accepts many arguments, so I'm not sure to understand why `Config.from_file` would be any different.

**Comment by DanCardin** [comment]
This is a bug/side-effect introduced by support for method subcommands.
