### ISSUE TITLE
bug: Literal with multiple values not supported

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#18]
This works:

```python
test: Annotated[Literal["hey"] | Literal["ho"], Doc("testing.")] = "hey"
```

...but triggers quality warnings, for example:

> Multiple literal members in a union. Use a single literal, e.g. `Literal["hey", "ho"]`Ruff[PYI030](https://docs.astral.sh/ruff/rules/unnecessary-literal-union)

This fails:

```python
test: Annotated[Literal["hey", "ho"], Doc("testing.")] = "hey"
```

Traceback:

```python
Traceback (most recent call last):
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/bin/insiders", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/data/dev/insiders/insiders/src/insiders/cli.py", line 150, in main
    return cappa.invoke(
           ^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/base.py", line 115, in invoke
    command, parsed_command, instance = Command.parse_command(
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/command.py", line 135, in parse_command
    command = cls.collect(command)
              ^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/command.py", line 112, in collect
    arg_def: Arg = Arg.collect(field, type_hint, fallback_help=arg_help)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/arg.py", line 130, in collect
    return arg.normalize(annotation, fallback_help=fallback_help)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/arg.py", line 150, in normalize
    parse = infer_parse(self, annotation)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/arg.py", line 328, in infer_parse
    return parse_value(annotation)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/annotation.py", line 47, in parse_value
    return parse_literal(*type_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: parse_literal() takes 1 positional argument but 2 were given
```

**Comment by DanCardin** [comment]
ooo. somehow I didn't realize that multiple literals could be used in a single one. definitely makes sense in retrospect
