### ISSUE TITLE
bug: Cappa tries to pass dataclass classvar as keyword argument

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#181]
```python
from __future__ import annotations

import sys
import cappa
from dataclasses import dataclass
from typing import ClassVar


@cappa.command(name="command")
@dataclass(kw_only=True)
class Command:
    _CONFIG: ClassVar[str] = "config.toml"

    arg: int = 0

    def __call__(self):
        print("Command called")



def main(args: list[str] | None = None) -> int:
    return cappa.invoke(Command, argv=args)


if __name__ == "__main__":
    sys.exit(main())
```

```pytb
Traceback (most recent call last):
  File "/media/data/dev/insiders-project/repro.py", line 26, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/data/dev/insiders-project/repro.py", line 22, in main
    return cappa.invoke(Command, argv=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/base.py", line 131, in invoke
    command, parsed_command, instance, concrete_output = parse_command(
                                                         ^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/base.py", line 247, in parse_command
    command, parsed_command, instance = Command.parse_command(
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/command.py", line 188, in parse_command
    result = command.map_result(command, prog, parsed_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders-project/.venv/lib/python3.12/site-packages/cappa/command.py", line 239, in map_result
    return command.cmd_cls(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Command.__init__() got an unexpected keyword argument '_CONFIG'
```

**Comment by pawamoy** [comment]
Looks like the class variable is shifting everything:

![cappa-shift](https://github.com/user-attachments/assets/7bf011fa-3a9d-4377-b8b5-b3ca728af6d5)

(look at short flags in the watch pane, and the subcommand being assigned to `_CONFIG` in the variables pane)

**Comment by pawamoy** [comment]
My investigation tells me that `DataclassField` should maybe use `dataclasses.fields(typ)` instead of `typ.__dataclasses_fields__`, as the former correctly ignores classvars:

```python
"_CONFIG" in command.cmd_cls.__dataclass_fields__   # True
"_CONFIG" in dataclasses.fields(command.cmd_cls)  # False
```

https://docs.python.org/3/library/dataclasses.html#dataclasses.fields

**Comment by DanCardin** [comment]
It seems to pass tests, i cannot for the life of me tell why I would have used that field instead of the `fields` function...

Yea feel free to send a PR! If it's accompanied by a classvar test and a `CHANGELOG` entry, feel free to also bump the patch version and i can release it directly.

**Comment by pawamoy** [comment]
Working on it!

**Comment by pawamoy** [comment]
I'll leave the changelog update and version bump to you this time :smile:
