### ISSUE TITLE
suggestion: Don't require `invoke` along the subcommand chain?

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#42]
Given this script:

```python
# invoke.py
import cappa


@cappa.command(name="subsub")
class SubSubCommand:
    """Sub-subcommand."""

    def __call__(self) -> int:
        print("reached")
        return 0


@cappa.command(name="sub")
class SubCommand:
    """Subcommand."""
    subcommand: cappa.Subcommands[SubSubCommand]


@cappa.command(name="invoke.py")
class MainCommand:
    subcommand: cappa.Subcommands[SubCommand]


def main() -> int:
    return cappa.invoke(MainCommand, backend=cappa.backend)


if __name__ == "__main__":
    raise SystemExit(main())
```

...executing `python invoke.py sub subsub` fails with:

```python
Traceback (most recent call last):
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/invoke.py", line 41, in invoke_callable
    fn: Callable = resolve_invoke_handler(parsed_command, instance)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/invoke.py", line 93, in resolve_invoke_handler
    raise InvokeResolutionError(
cappa.invoke.InvokeResolutionError: Cannot call `invoke` for a command which does not have an invoke handler: <class '__main__.SubSubCommand'>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/data/dev/insiders/insiders/invoke.py", line 29, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/media/data/dev/insiders/insiders/invoke.py", line 25, in main
    return cappa.invoke(MainCommand, argv=args, backend=cappa.backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/base.py", line 134, in invoke
    return invoke_callable(command, parsed_command, instance, output=output, deps=deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/invoke.py", line 48, in invoke_callable
    raise InvokeResolutionError(
cappa.invoke.InvokeResolutionError: Failed to invoke <class '__main__.SubSubCommand'> due to resolution failure.
```

I was expecting it to automatically execute the last subcommand's `__call__` method. But maybe that would be too implicit :thinking: 

Adding `__call__` method along the chain works fine:

```python
# invoke.py
import cappa


@cappa.command(name="subsub")
class SubSubCommand:
    """Sub-subcommand."""

    def __call__(self) -> int:
        print("reached")
        return 0


@cappa.command(name="sub")
class SubCommand:
    """Subcommand."""
    subcommand: cappa.Subcommands[SubSubCommand]

    def __call__(self) -> int:
        return self.subcommand()


@cappa.command(name="invoke.py")
class MainCommand:
    subcommand: cappa.Subcommands[SubCommand]

    def __call__(self) -> int:
        return self.subcommand()


def main() -> int:
    return cappa.invoke(MainCommand, backend=cappa.backend)


if __name__ == "__main__":
    raise SystemExit(main())
```

**Comment by DanCardin** [comment]
I think that's probably a good idea and certainly doable. I originally hadn't with the thinking that any dependency up the chain might be "called", so it'd be required at some level anyways. but if that subcommand's subcommands are also required, then that `__call__` is just dead code.
