### ISSUE TITLE
question/bug: Specifying a subcommand's name

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#8]
Following the docs, I created a dataclass to hold the subcommand options (shortened to one for brevity):

```python
@dataclass
class OptsCreate:
    """Create a pair of public/insiders repositories."""

    namespace: Annotated[str, cappa.Arg(short="-n", long=True)]
```

Then I declare my main options:

```python
@dataclass
class Opts:
    create: cappa.Subcommands[OptsCreate]
```

But when I run `progname -h`, it shows that the command is named `opts-create`:

```console
% pdm run progname -h
usage: progname [-h] [-V] {opts-create} ...

Options:
  -h, --help            Print help and exit.
  -V, --0.1.dev2+g608aacb.d20231017.editable
                        Print the version of the program and exit.

Subcommands:

  {opts-create}
    opts-create         Create a pair of public/insiders repositories.
```

I thought the subcommand would use the name of the attribute in the main options (`create`) :thinking: 

So instead I tried this:

```python
@dataclass
class Opts:
    create: Annotated[OptsCreate, cappa.Subcommand(name="create")]
```

But got the same result: subcommand is still named opts-create.

Is this a bug/oversight, or users are really expected to name their dataclass after the command name?
Maybe there's another way that I missed in the docs?

**Comment by pawamoy** [comment]
Thanks for your help!

OK, it's tidier this way indeed. However I'm getting this traceback now :thinking: 

```python
Traceback (most recent call last):
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/bin/insiders", line 5, in <module>
    from insiders.cli import main
  File "/media/data/dev/insiders/insiders/src/insiders/cli.py", line 27, in <module>
    @cappa.command("create")
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/base.py", line 170, in command
    return wrapper(_cls)
           ^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/base.py", line 156, in wrapper
    if not detect(_decorated_cls):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/class_inspect.py", line 22, in detect
    return bool(ClassTypes.from_cls(cls))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/class_inspect.py", line 46, in from_cls
    if issubclass(obj, BaseModel):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class
```

**Comment by pawamoy** [comment]
Ah, the command decorator expects name to be a keyword-only argument I think.
