### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

### ISSUE THREAD

**Issue by wu-clan** [DanCardin/cappa#99]
Hi, @DanCardin 

I used the `|` symbol in the cli program, and introduced `from __future__ import annotations` in the header. 

This error occurred when I was testing in the local python3.9, and the full stack is as follows:
```
Traceback (most recent call last):
  File "D:\git_projects\httpfpt\httpfpt\cli.py", line 316, in <module>
    cappa.invoke(HttpFptCLI)
  File "D:\git_projects\httpfpt\.venv\lib\site-packages\cappa\base.py", line 121, in invoke
    command, parsed_command, instance, concrete_output = parse_command(
  File "D:\git_projects\httpfpt\.venv\lib\site-packages\cappa\base.py", line 222, in parse_command
    command: Command = collect(
  File "D:\git_projects\httpfpt\.venv\lib\site-packages\cappa\base.py", line 308, in collect
    command = Command.collect(command)
    command = Command.collect(command)
  File "D:\git_projects\httpfpt\.venv\lib\site-packages\cappa\command.py", line 120, in collect
    type_hints = get_type_hints(command.cmd_cls, include_extras=True)
  File "D:\git_projects\httpfpt\.venv\lib\site-packages\typing_extensions.py", line 1104, in get_type_hints
    hint = typing.get_type_hints(
  File "C:\Users\13522\.yen_pythons\3.9.18\python\lib\typing.py", line 1459, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "C:\Users\13522\.yen_pythons\3.9.18\python\lib\typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\13522\.yen_pythons\3.9.18\python\lib\typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'
```

I'm not sure if this has anything to do with pydantic >= 6.0, because it introduced https://github.com/alexmojaki/eval_type_backport to fix its own problems in this version.

**Comment by wu-clan** [comment]
The error above occurred at `Annotated[List[str] | None, cappa.Arg()]`, and the same issue exists with `Subcommands[x | y | z]`.

**Comment by DanCardin** [comment]
I dont think this is especially surprising. This syntax doesn't yet work in 3.9, and you're only getting around it by the `__future__ import annotations`. However cappa ultimately needs to evaluate all the annotations, which forces python to eventually parse the syntax (and it cant).

With that said, https://github.com/alexmojaki/eval_type_backport seems to be a newly arrived at solution, that we might be able to adopt for python versions <3.10

**Comment by DanCardin** [comment]
Cappa needs to evaluate the type hints which may or may not be coming back as strings from the source class, whether it's a pydantic (also it wouldn't work in pydantic v1 source classes) base or not. Based on my tests so far, it seems to be "fairly straightforward" to adopt, if inlining a copy of `get_type_hints` can be considered fairly straightforward.

**Comment by DanCardin** [comment]
If you wouldn't mind testing the branch to make sure it works ahead of my merge, I'd appreciate it!

**Comment by wu-clan** [comment]
Sorry I'm late. I'll test it as soon as possible.

**Comment by wu-clan** [comment]
Hi, @DanCardin 

I built and installed and tested 0.16.3 locally, and everything looked fine.
